// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gov/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	StartingProposalID uint64      `protobuf:"varint,1,opt,name=StartingProposalID,proto3" json:"starting_proposal_id" yaml:"starting_proposal_id"`
	Votes              []Vote      `protobuf:"bytes,2,rep,name=Votes,proto3" json:"votes" yaml:"votes"`
	Proposals          []Proposal  `protobuf:"bytes,3,rep,name=Proposals,proto3" json:"proposal" yaml:"proposal"`
	TallyParams        TallyParams `protobuf:"bytes,4,opt,name=TallyParams,proto3" json:"tally_params" yaml:"tally_params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6985d8d7b5fce28, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetStartingProposalID() uint64 {
	if m != nil {
		return m.StartingProposalID
	}
	return 0
}

func (m *GenesisState) GetVotes() []Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *GenesisState) GetProposals() []Proposal {
	if m != nil {
		return m.Proposals
	}
	return nil
}

func (m *GenesisState) GetTallyParams() TallyParams {
	if m != nil {
		return m.TallyParams
	}
	return TallyParams{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "gov.GenesisState")
}

func init() { proto.RegisterFile("gov/genesis.proto", fileDescriptor_f6985d8d7b5fce28) }

var fileDescriptor_f6985d8d7b5fce28 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x6a, 0xea, 0x40,
	0x14, 0xc6, 0x13, 0xff, 0x5c, 0xae, 0x51, 0xb9, 0xf7, 0xe6, 0xba, 0x08, 0x96, 0x66, 0x24, 0xdd,
	0x08, 0x45, 0x03, 0x76, 0x51, 0xe8, 0xa2, 0x8b, 0x50, 0x90, 0xee, 0x24, 0x96, 0x2e, 0xba, 0x09,
	0xa3, 0x0e, 0x43, 0x68, 0xe2, 0x09, 0x99, 0x69, 0xa8, 0x6f, 0xd1, 0xc7, 0x72, 0xe9, 0xb2, 0xab,
	0xa1, 0xe8, 0xce, 0x65, 0x9e, 0xa0, 0x64, 0x26, 0xa1, 0x2e, 0xdc, 0xcd, 0xf7, 0xfb, 0xe6, 0xfc,
	0x38, 0x70, 0x8c, 0x7f, 0x14, 0x32, 0x97, 0x92, 0x35, 0x61, 0x21, 0x1b, 0x27, 0x29, 0x70, 0x30,
	0xeb, 0x14, 0xb2, 0x7e, 0x8f, 0x02, 0x05, 0x99, 0xdd, 0xe2, 0xa5, 0xaa, 0x7e, 0x57, 0xfe, 0x86,
	0x4c, 0x45, 0xe7, 0x58, 0x33, 0x3a, 0x53, 0x35, 0x3b, 0xe7, 0x98, 0x13, 0x93, 0x1a, 0xe6, 0x9c,
	0xe3, 0x94, 0x87, 0x6b, 0x3a, 0x4b, 0x21, 0x01, 0x86, 0xa3, 0xc7, 0x07, 0x4b, 0x1f, 0xe8, 0xc3,
	0x86, 0x77, 0x7b, 0x14, 0xa8, 0xc7, 0xca, 0x36, 0x48, 0xca, 0x3a, 0x08, 0x57, 0xb9, 0x40, 0x17,
	0x1b, 0x1c, 0x47, 0x77, 0xce, 0xb9, 0xd6, 0xf1, 0xcf, 0x28, 0xcd, 0x7b, 0xa3, 0xf9, 0x0c, 0x9c,
	0x30, 0xab, 0x36, 0xa8, 0x0f, 0xdb, 0x93, 0xd6, 0xb8, 0x58, 0xaa, 0x20, 0xde, 0xe5, 0x56, 0x20,
	0xed, 0x28, 0x50, 0x33, 0x2b, 0xfa, 0x5c, 0xa0, 0x8e, 0x72, 0xcb, 0xe8, 0xf8, 0x6a, 0xcc, 0x9c,
	0x19, 0xad, 0xca, 0xc6, 0xac, 0xba, 0x74, 0x74, 0xa5, 0xa3, 0xa2, 0xde, 0x55, 0xe9, 0xf9, 0x5d,
	0xed, 0x92, 0x0b, 0xf4, 0x47, 0xa9, 0x2a, 0xe2, 0xf8, 0x3f, 0x12, 0x33, 0x30, 0xda, 0x4f, 0x38,
	0x8a, 0x36, 0x33, 0x9c, 0xe2, 0x98, 0x59, 0x8d, 0x81, 0x3e, 0x6c, 0x4f, 0xfe, 0x4a, 0xe7, 0x09,
	0xf7, 0xae, 0x4b, 0x6d, 0x87, 0x17, 0x30, 0x48, 0x24, 0xcd, 0x05, 0xfa, 0xaf, 0xd4, 0xa7, 0xd4,
	0xf1, 0x4f, 0x8d, 0xde, 0x74, 0xbb, 0xb7, 0xf5, 0xdd, 0xde, 0xd6, 0xbf, 0xf6, 0xb6, 0xfe, 0x71,
	0xb0, 0xb5, 0xdd, 0xc1, 0xd6, 0x3e, 0x0f, 0xb6, 0xf6, 0x32, 0x5a, 0x84, 0x7c, 0xf1, 0xb6, 0x7c,
	0x25, 0x7c, 0x0c, 0x29, 0x75, 0x57, 0x64, 0x19, 0xc6, 0x38, 0xe2, 0x04, 0xc7, 0x2e, 0x85, 0xd1,
	0x1a, 0x56, 0xc4, 0x7d, 0x2f, 0xae, 0xe6, 0xf2, 0x4d, 0x42, 0xd8, 0xe2, 0x97, 0x3c, 0xde, 0xcd,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x6a, 0x5e, 0xef, 0xfb, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TallyParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Proposals) > 0 {
		for iNdEx := len(m.Proposals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Proposals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Votes) > 0 {
		for iNdEx := len(m.Votes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Votes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.StartingProposalID != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.StartingProposalID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StartingProposalID != 0 {
		n += 1 + sovGenesis(uint64(m.StartingProposalID))
	}
	if len(m.Votes) > 0 {
		for _, e := range m.Votes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Proposals) > 0 {
		for _, e := range m.Proposals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.TallyParams.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartingProposalID", wireType)
			}
			m.StartingProposalID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartingProposalID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Votes = append(m.Votes, Vote{})
			if err := m.Votes[len(m.Votes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposals = append(m.Proposals, Proposal{})
			if err := m.Proposals[len(m.Proposals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TallyParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TallyParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
