image: golang:1.13

pipelines:
  branches:
    develop:
      - step:
          name: Build
          script:
            - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_FULL_NAME}"
            - mkdir -pv "${PACKAGE_PATH}"
            - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
            - export GO111MODULE=on
            - cd "${PACKAGE_PATH}"
            - go get ./...
            - make all
      - step:
          name: Deploy (Frankrurt)
          script:
            - pipe: atlassian/ssh-run:0.2.4
              variables:
                SSH_USER: 'centos'
                SERVER: '139.59.133.148'
                MODE: 'command'
                COMMAND: './ci-scripts/update.sh'