image: golang:1.13

build: &build
  - step:
      name: Build
      script:
        - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_FULL_NAME}"
        - mkdir -pv "${PACKAGE_PATH}"
        - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
        - export GO111MODULE=on
        - cd "${PACKAGE_PATH}"
        - go get ./...
        - make all
        - mkdir ${BITBUCKET_CLONE_DIR}/build
        - cp ${GOPATH}/bin/* ${BITBUCKET_CLONE_DIR}/build
      artifacts:
        - build/deccli
        - build/decd

deploy-script: &deploy-script
  script:
    - pipe: atlassian/sftp-deploy:0.5.4
      variables:
        USER: $USER
        SSH_KEY: $SSHKEY
        SERVER: $HOST
        LOCAL_PATH: 'build/*'
        REMOTE_PATH: '/home/$USER/decimal/'
        DEBUG: 'true'

pipelines:
  tags:
    'wipe/*':
      - parallel:
          - step:
              name: Stop on host 01
              script:
                - pipe: atlassian/ssh-run:0.2.5
                  variables:
                    SSH_USER: $HOST01_USER
                    SERVER: $HOST01_HOST
                    SSH_KEY: $HOST01_KEY
                    COMMAND: 'sudo systemctl stop decd'
                    MODE: 'command'
          - step:
              name: Stop on host 02
              script:
                - pipe: atlassian/ssh-run:0.2.5
                  variables:
                    SSH_USER: $HOST02_USER
                    SERVER: $HOST02_HOST
                    SSH_KEY: $HOST02_KEY
                    COMMAND: 'sudo systemctl stop decd'
                    MODE: 'command'
          - step:
              name: Stop on host 03
              script:
                - pipe: atlassian/ssh-run:0.2.5
                  variables:
                    SSH_USER: $HOST03_USER
                    SERVER: $HOST03_HOST
                    SSH_KEY: $HOST03_KEY
                    COMMAND: 'sudo systemctl stop decd'
                    MODE: 'command'
      - step:
          name: Restart blockchain on validator node.
          script:
            - pipe: atlassian/ssh-run:0.2.5
              variables:
                SSH_USER: $HOST01_USER
                SERVER: $HOST01_HOST
                SSH_KEY: $HOST01_KEY
                COMMAND: 'ci-scripts/restart_validator.sh'
                MODE: 'script'
      - parallel:
          - step:
              name: Restart blockchain on host 02.
              script:
                - pipe: atlassian/ssh-run:0.2.5
                  variables:
                    SSH_USER: $HOST02_USER
                    SERVER: $HOST02_HOST
                    SSH_KEY: $HOST02_KEY
                    COMMAND: 'ci-scripts/restart_node.sh'
                    MODE: 'script'

          - step:
              name: Restart blockchain on host 03.
              script:
                - pipe: atlassian/ssh-run:0.2.5
                  variables:
                    SSH_USER: $HOST03_USER
                    SERVER: $HOST03_HOST
                    SSH_KEY: $HOST03_KEY
                    COMMAND: 'ci-scripts/restart_node.sh'
                    MODE: 'script'

  branches:
    develop:
      - <<: *build
      - parallel:
          - step:
              name: Stop on host 01
              script:
                - pipe: atlassian/ssh-run:0.2.5
                  variables:
                    SSH_USER: $HOST01_USER
                    SERVER: $HOST01_HOST
                    SSH_KEY: $HOST01_KEY
                    COMMAND: 'sudo systemctl stop decd'
                    MODE: 'command'
          - step:
              name: Stop on host 02
              script:
                - pipe: atlassian/ssh-run:0.2.5
                  variables:
                    SSH_USER: $HOST02_USER
                    SERVER: $HOST02_HOST
                    SSH_KEY: $HOST02_KEY
                    COMMAND: 'sudo systemctl stop decd'
                    MODE: 'command'
          - step:
              name: Stop on host 03
              script:
                - pipe: atlassian/ssh-run:0.2.5
                  variables:
                    SSH_USER: $HOST03_USER
                    SERVER: $HOST03_HOST
                    SSH_KEY: $HOST03_KEY
                    COMMAND: 'sudo systemctl stop decd'
                    MODE: 'command'
      - parallel:
          - step:
              name: Deploy on host 01
              deployment: test01
              <<: *deploy-script
          - step:
              name: Deploy on host 02
              deployment: test02
              <<: *deploy-script
          - step:
              name: Deploy on host 03
              deployment: test03
              <<: *deploy-script