image: golang:1.13

pipelines:
  branches:
    develop:
      - step:
          name: Build
          script:
            - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_FULL_NAME}"
            - mkdir -pv "${PACKAGE_PATH}"
            - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
            - export GO111MODULE=on
            - cd "${PACKAGE_PATH}"
            - go get ./...
            - make all
          artifacts:
            - go/bin/*
      - parallel:
          - step:
              name: Deploy (Host 01)
              script:
                - pipe: atlassian/ssh-run:0.2.4
                  variables:
                    SSH_USER: $HOST01_USER
                    SERVER: $HOST01_HOST
                    MODE: 'script'
                    COMMAND: './ci-scripts/update.sh'
                    SSH_KEY: $HOST01_KEY

          - step:
              name: Deploy (Host 02)
              script:
                - pipe: atlassian/ssh-run:0.2.4
                  variables:
                    SSH_USER: $HOST02_USER
                    SERVER: $HOST02_HOST
                    MODE: 'script'
                    COMMAND: './ci-scripts/update.sh'
                    SSH_KEY: $HOST02_KEY

          - step:
              name: Deploy (Host 03)
              script:
                - pipe: atlassian/ssh-run:0.2.4
                  variables:
                    SSH_USER: $HOST03_USER
                    SERVER: $HOST03_HOST
                    MODE: 'script'
                    COMMAND: './ci-scripts/update.sh'
                    SSH_KEY: $HOST03_KEY