image: golang:1.13

build: &build
  - step:
      name: Build
      script:
        - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_FULL_NAME}"
        - mkdir -pv "${PACKAGE_PATH}"
        - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
        - export GO111MODULE=on
        - cd "${PACKAGE_PATH}"
        - go get ./...
        - make all
        - mkdir ${BITBUCKET_CLONE_DIR}/build
        - cp ${GOPATH}/bin/* ${BITBUCKET_CLONE_DIR}/build
      artifacts:
        - build/deccli
        - build/decd

stop-pipe: &stop-pipe
  - pipe: atlassian/ssh-run:0.2.5
      variables:
        SSH_USER: $USER
        SERVER: $HOST
        SSH_KEY: $SSHKEY
        COMMAND: 'sudo systemctl stop decd'
        MODE: 'command'

deploy-pipe: &deploy-pipe
  - pipe: atlassian/sftp-deploy:0.5.4
      variables:
        USER: $USER
        SSH_KEY: $SSHKEY
        SERVER: $HOST
        LOCAL_PATH: 'build/*'
        REMOTE_PATH: '/home/$USER/decimal/'
        DEBUG: 'true'

restart-pipe: &restart-pipe
  - pipe: atlassian/ssh-run:0.2.5
      variables:
        SSH_USER: $USER
        SERVER: $HOST
        SSH_KEY: $SSHKEY
        COMMAND: 'sudo systemctl restart decd'
        MODE: 'command'

deploy-script: &deploy-script
  script:
    - pipe1:
      <<: *stop-pipe
    - pipe2:
      <<: *deploy-pipe
    - pipe3:
      <<: *restart-pipe

wipe-validator-pipe: &wipe-validator-pipe
  - pipe: atlassian/ssh-run:0.2.5
      variables:
        SSH_USER: $USER
        SERVER: $HOST
        SSH_KEY: $SSHKEY
        COMMAND: './ci-scripts/init_blockchain.sh'
        MODE: 'script'

update-configs-pipe: &update-configs-pipe
  - pipe: atlassian/ssh-run:0.2.5
      variables:
        SSH_USER: $USER
        SERVER: $HOST
        SSH_KEY: $SSHKEY
        COMMAND: './ci-scripts/update_configs.sh'
        MODE: 'script'

wipe-validator-script: &wipe-validator-script
  script:
    - pipe1:
      <<: *stop-pipe
    - pipe2:
      <<: *wipe-validator-pipe
    - pipe3:
      <<: *restart-pipe

update-config-script:
  script:
    - pipe1:
      <<: *stop-pipe
    - pipe2:
      <<: *update-configs-pipe
    - pipe3:
      <<: *restart-pipe


pipelines:
  tags:
    'wipe/*':
      - step:
          name: Wiping validator
          deployment: test01
          <<: *wipe-validator-script
      - parallel:
          - step:
              name: Update configs on Host 02
              deployment: test02
              <<: *deploy-script
          - step:
              name: Update configs on Host 03
              deployment: test03
              <<: *deploy-script

  branches:
    develop:
      - <<: *build
      - step:
          name: Deploy to validator node (Host 01)
          deployment: test01
          <<: *deploy-script
      - parallel:
          - step:
              name: Deploy to Host 02
              deployment: test02
              <<: *deploy-script
          - step:
              name: Deploy to Host 03
              deployment: test03
              <<: *deploy-script