image: golang:1.13

build: &build
  - step:
      name: Build
      script:
        - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_FULL_NAME}"
        - mkdir -pv "${PACKAGE_PATH}"
        - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
        - export GO111MODULE=on
        - cd "${PACKAGE_PATH}"
        - go get ./...
        - make all
        - mkdir ${BITBUCKET_CLONE_DIR}/build
        - cp ${GOPATH}/bin/* ${BITBUCKET_CLONE_DIR}/build
      artifacts:
        - build/deccli
        - build/decd

deploy-script: &deploy-script
  script:
    - pipe: atlassian/sftp-deploy:0.5.4
      variables:
        USER: $USER
        SSH_KEY: $SSHKEY
        SERVER: $HOST
        LOCAL_PATH: 'build/*'
        REMOTE_PATH: '/home/$USER/decimal/'

pipelines:
  branches:
    develop:
      - <<: *build
      - parallel:
          - step:
              name: Deploy on host 01
              deployment: test01
              <<: *deploy-script
          - step:
              name: Deploy on host 02
              deployment: test02
              <<: *deploy-script
          - step:
              name: Deploy on host 03
              deployment: test03
              <<: *deploy-script