image: golang:1.13

build: &build
  - step:
      name: Build
      script:
        - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_FULL_NAME}"
        - mkdir -pv "${PACKAGE_PATH}"
        - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
        - export GO111MODULE=on
        - cd "${PACKAGE_PATH}"
        - go get ./...
        - make all
        - mkdir ${BITBUCKET_CLONE_DIR}/build
        - cp ${GOPATH}/bin/* ${BITBUCKET_CLONE_DIR}/build
      artifacts:
        - build/deccli
        - build/decd

deploy-script: &deploy-script
  script:
    - pipe: atlassian/sftp-deploy:0.5.4
      variables:
        USER: $USER
        SSH_KEY: $SSHKEY
        SERVER: $HOST
        LOCAL_PATH: 'build/*'
        REMOTE_PATH: '/home/$USER/decimal/'

deploy-01: &deploy-01
  - step:
      name: Deploy on Host 01
      deployment: test01
      script:
        - pipe: atlassian/sftp-deploy:0.5.4
          variables:
            USER: $HOST01_USER
            SSH_KEY: $HOST01_KEY
            SERVER: $HOST01_HOST
            LOCAL_PATH: 'build'
            REMOTE_PATH: '/home/$HOST01_USER/decimal'

deploy-02: &deploy-02
  - step:
      name: Deploy on Host 02
      deployment: test02
      script:
        - pipe: atlassian/sftp-deploy:0.5.4
          variables:
            USER: $HOST02_USER
            SSH_KEY: $HOST02_KEY
            SERVER: $HOST02_HOST
            LOCAL_PATH: 'build'
            REMOTE_PATH: '/home/$HOST02_USER/decimal'

deploy-03: &deploy-03
  - step:
      name: Deploy on Host 03
      deployment: test03
      script:
        - pipe: atlassian/sftp-deploy:0.5.4
          variables:
            USER: $HOST03_USER
            SSH_KEY: $HOST03_KEY
            SERVER: $HOST03_HOST
            LOCAL_PATH: 'build'
            REMOTE_PATH: '/home/$HOST03_USER/decimal'

pipelines:
  branches:
    develop:
      - <<: *build
      - parallel:
          - step:
              name: Deploy on host 01
              deployment: test01
              <<: *deploy-script
          - step:
              name: Deploy on host 02
              deployment: test02
              <<: *deploy-script
          - step:
              name: Deploy on host 03
              deployment: test03
              <<: *deploy-script