---
# tasks file for check & stop service & create it if not exist
- name: Check if decd Service Exists
  stat: path={{ systemd_path }}/{{ service_name_decd }}
  register: service_status_decd

- name: Check if deccli Service Exists
  stat: path={{ systemd_path }}/{{ service_name_rest }}
  register: service_status_rest

- name: Stop service decd, if started
  service:
    name: '{{ service_name_decd }}'
    state: stopped
  when: service_status_decd.stat.exists
  become: yes

- name: Stop service decd rest, if started
  service:
    name: '{{ service_name_rest }}'
    state: stopped
  when: service_status_rest.stat.exists
  become: yes

- name: Register decd service
  copy:
    src: ./{{ service_name_decd }}
    dest: '{{ systemd_path }}/{{ service_name_decd }}'
  when: service_status_decd.stat.exists == False
  become: yes

- name: Register decd rest service
  copy:
    src: ./{{ service_name_rest }}
    dest: '{{ systemd_path }}/{{ service_name_rest }}'
  when: service_status_rest.stat.exists == False
  become: yes
