---
# tasks file for check & stop service & create it if not exist
- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes
  become: yes

- name: Run service decd
  service:
    name: '{{ service_name_decd }}'
    state: started
    enabled: yes
  become: yes

- name: Run service decd rest
  service:
    name: '{{ service_name_rest }}'
    state: started
    enabled: yes
  become: yes
