---
- name: Update Decimal decd/rest services (systemd)
  hosts: all
  gather_facts: False

  roles:
    - role: decimal-service
      vars:
        mode: stop

    - role: decimal-service
      vars:
        mode: start
