---
- name: Install Decimal Node with Full Init!
  hosts: fail
  gather_facts: True

  roles:
    - role: decimal-service
      vars:
        srv_mode: stop

    - role: decimal-init
      vars:
        mode: '{{ mode }}' # external variable: mode = master | slave

    - role: decimal-service
      vars:
        srv_mode: start
