---
- name: Update Decimal decd/rest services (systemd)
  hosts: hosts
  gather_facts: False

  roles:
    - role: decimal-service
      vars:
        srv_mode: stop

    - role: decimal-service
      vars:
        srv_mode: start
