---
- name: Update Decimal Node (only bin files)
  hosts: all
  gather_facts: True

  roles:
    - role: decimal-service
      vars:
        srv_mode: stop

    - role: decimal-update

    - role: decimal-service
      vars:
        srv_mode: start
