---
- name: reload systemctl
  systemd:
    daemon_reload: yes
  become: yes

- name: run service Explorer Indexer Worker
  service:
    name: '{{ service_name_worker }}'
    state: started
    enabled: yes
  become: yes
