---
- name: reload systemctl
  command: systemctl daemon-reload
  become: yes

- name: run service Explorer Indexer Worker
  service:
    name: '{{ service_name_worker }}'
    state: started
    enabled: yes
  become: yes

- name: run service Explorer Indexer
  shell: pm2 start all