// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: validator/delegation_nft.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DelegationNFT struct {
	DelegatorAddress github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=DelegatorAddress,proto3,customtype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"delegator_address" yaml:"delegator_address"`
	ValidatorAddress github_com_cosmos_cosmos_sdk_types.ValAddress `protobuf:"bytes,2,opt,name=ValidatorAddress,proto3,customtype=github.com/cosmos/cosmos-sdk/types.ValAddress" json:"validator_address" yaml:"validator_address"`
	Denom            string                                        `protobuf:"bytes,3,opt,name=Denom,proto3" json:"denom" yaml:"denom"`
	TokenID          string                                        `protobuf:"bytes,4,opt,name=TokenID,proto3" json:"token_id" yaml:"token_id"`
	Quantity         github_com_cosmos_cosmos_sdk_types.Int        `protobuf:"bytes,5,opt,name=Quantity,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"quantity" yaml:"quantity"`
	Coin             github_com_cosmos_cosmos_sdk_types.Coin       `protobuf:"bytes,6,opt,name=Coin,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"coin" yaml:"coin"`
}

func (m *DelegationNFT) Reset()         { *m = DelegationNFT{} }
func (m *DelegationNFT) String() string { return proto.CompactTextString(m) }
func (*DelegationNFT) ProtoMessage()    {}
func (*DelegationNFT) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc0a72f3637630f, []int{0}
}
func (m *DelegationNFT) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegationNFT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegationNFT.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegationNFT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationNFT.Merge(m, src)
}
func (m *DelegationNFT) XXX_Size() int {
	return m.Size()
}
func (m *DelegationNFT) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationNFT.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationNFT proto.InternalMessageInfo

type UnbondingDelegationNFTEntry struct {
	CreationHeight int64                                   `protobuf:"varint,1,opt,name=CreationHeight,proto3" json:"creation_height" yaml:"creation_height"`
	CompletionTime time.Time                               `protobuf:"bytes,2,opt,name=CompletionTime,proto3,customtype=time.Time" json:"completion_time" yaml:"completion_time"`
	Denom          string                                  `protobuf:"bytes,3,opt,name=Denom,proto3" json:"denom" yaml:"denom"`
	TokenID        string                                  `protobuf:"bytes,4,opt,name=TokenID,proto3" json:"token_id" yaml:"token_id"`
	Quantity       github_com_cosmos_cosmos_sdk_types.Int  `protobuf:"bytes,5,opt,name=Quantity,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"quantity" yaml:"quantity"`
	Balance        github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,6,opt,name=Balance,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"balance" yaml:"balance"`
}

func (m *UnbondingDelegationNFTEntry) Reset()         { *m = UnbondingDelegationNFTEntry{} }
func (m *UnbondingDelegationNFTEntry) String() string { return proto.CompactTextString(m) }
func (*UnbondingDelegationNFTEntry) ProtoMessage()    {}
func (*UnbondingDelegationNFTEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc0a72f3637630f, []int{1}
}
func (m *UnbondingDelegationNFTEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnbondingDelegationNFTEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnbondingDelegationNFTEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnbondingDelegationNFTEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbondingDelegationNFTEntry.Merge(m, src)
}
func (m *UnbondingDelegationNFTEntry) XXX_Size() int {
	return m.Size()
}
func (m *UnbondingDelegationNFTEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbondingDelegationNFTEntry.DiscardUnknown(m)
}

var xxx_messageInfo_UnbondingDelegationNFTEntry proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DelegationNFT)(nil), "validator.DelegationNFT")
	proto.RegisterType((*UnbondingDelegationNFTEntry)(nil), "validator.UnbondingDelegationNFTEntry")
}

func init() { proto.RegisterFile("validator/delegation_nft.proto", fileDescriptor_5cc0a72f3637630f) }

var fileDescriptor_5cc0a72f3637630f = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x6d, 0x9a, 0xb6, 0x89, 0x29, 0x29, 0x58, 0x08, 0x19, 0x90, 0x7c, 0x95, 0x07, 0xe8,
	0x92, 0x78, 0xe8, 0x44, 0x07, 0xa4, 0x26, 0xa1, 0xa2, 0x12, 0x45, 0xc2, 0x4a, 0x3b, 0x74, 0x89,
	0xce, 0xbe, 0x8b, 0x73, 0x8a, 0x7d, 0x17, 0xec, 0x0b, 0x22, 0xdf, 0x80, 0x11, 0xf1, 0x09, 0xba,
	0xf0, 0x5d, 0x3a, 0x76, 0x44, 0x0c, 0x27, 0x94, 0x2c, 0x28, 0xa3, 0x07, 0x66, 0xe4, 0xf3, 0x39,
	0x69, 0xc8, 0xd2, 0xae, 0x4c, 0x49, 0xfe, 0xff, 0xf7, 0xfe, 0xbf, 0xf7, 0xa2, 0xa7, 0x33, 0xec,
	0x4f, 0x30, 0x22, 0x08, 0x72, 0x96, 0xb8, 0x08, 0x47, 0x38, 0x84, 0x9c, 0x30, 0xda, 0xa3, 0x7d,
	0xde, 0x1c, 0x25, 0x8c, 0x33, 0xb3, 0xb6, 0xf0, 0x9f, 0x3d, 0x0e, 0x59, 0xc8, 0xa4, 0xea, 0xe6,
	0xdf, 0x8a, 0x02, 0xe7, 0x4f, 0xc5, 0x78, 0xd0, 0x59, 0x74, 0xbe, 0x3f, 0xee, 0x9a, 0xdf, 0x74,
	0xe3, 0xa1, 0x52, 0x58, 0x72, 0x84, 0x50, 0x82, 0xd3, 0xd4, 0xd2, 0xf7, 0xf4, 0xfd, 0x9d, 0x56,
	0xff, 0x4a, 0x00, 0xed, 0xa7, 0x00, 0x8d, 0x90, 0xf0, 0xc1, 0xd8, 0x6f, 0x06, 0x2c, 0x76, 0x03,
	0x96, 0xc6, 0x2c, 0x55, 0x1f, 0x8d, 0x14, 0x0d, 0x5d, 0x3e, 0x19, 0xe1, 0xb4, 0x79, 0x14, 0x04,
	0xaa, 0x79, 0x2e, 0xc0, 0x23, 0x54, 0x06, 0xf6, 0x60, 0x21, 0x66, 0x02, 0x58, 0x13, 0x18, 0x47,
	0x87, 0xce, 0x9a, 0xe5, 0x78, 0x6b, 0x7c, 0x39, 0xd4, 0x79, 0xb9, 0x4a, 0x39, 0xd4, 0xbd, 0x3b,
	0x0f, 0x75, 0x0e, 0xa3, 0x1b, 0x43, 0x2d, 0xfe, 0x9b, 0xf5, 0xa1, 0xd6, 0x2c, 0xc7, 0x5b, 0xe3,
	0x9b, 0xae, 0xb1, 0xd9, 0xc1, 0x94, 0xc5, 0xd6, 0xc6, 0x9e, 0xbe, 0x5f, 0x6b, 0x3d, 0x9d, 0x0b,
	0xb0, 0x89, 0x72, 0x21, 0x13, 0x60, 0xa7, 0x5c, 0x8e, 0xb2, 0xd8, 0xf1, 0x8a, 0x3a, 0xf3, 0x95,
	0xb1, 0xdd, 0x65, 0x43, 0x4c, 0x4f, 0x3a, 0x56, 0x45, 0xb6, 0x80, 0xb9, 0x00, 0x55, 0x9e, 0x4b,
	0x3d, 0x82, 0x32, 0x01, 0x76, 0x8b, 0xae, 0x52, 0x71, 0xbc, 0xb2, 0xde, 0x24, 0x46, 0xf5, 0xc3,
	0x18, 0x52, 0x4e, 0xf8, 0xc4, 0xda, 0x94, 0x7b, 0x9f, 0xaa, 0xbd, 0x5f, 0xdc, 0x62, 0xef, 0x13,
	0xca, 0x73, 0xd2, 0x47, 0x95, 0xb0, 0x24, 0x95, 0x8a, 0xe3, 0x2d, 0xe2, 0xcd, 0x0b, 0xa3, 0xd2,
	0x66, 0x84, 0x5a, 0x5b, 0x12, 0x73, 0xac, 0x30, 0x2f, 0x6f, 0x81, 0xc9, 0xdb, 0xe6, 0x02, 0x54,
	0x02, 0x46, 0x68, 0x26, 0xc0, 0xfd, 0x82, 0x91, 0xff, 0x72, 0x3c, 0x99, 0x79, 0x58, 0xfd, 0x72,
	0x09, 0xb4, 0xdf, 0x97, 0x40, 0x73, 0xbe, 0x57, 0x8c, 0xe7, 0x67, 0xd4, 0x67, 0x14, 0x11, 0x1a,
	0xae, 0x5c, 0xe0, 0x1b, 0xca, 0x93, 0x89, 0x79, 0x66, 0xd4, 0xdb, 0x09, 0x96, 0xda, 0x5b, 0x4c,
	0xc2, 0x01, 0x97, 0x37, 0xb8, 0xd1, 0x6a, 0xcc, 0x05, 0xd8, 0x0d, 0x94, 0xd3, 0x1b, 0x48, 0x2b,
	0x13, 0xe0, 0x89, 0x62, 0xad, 0x1a, 0x8e, 0xf7, 0x4f, 0x88, 0xd9, 0x37, 0xea, 0x6d, 0x16, 0x8f,
	0x22, 0x9c, 0x6b, 0x5d, 0x12, 0x63, 0x75, 0x45, 0xaf, 0xd5, 0x9a, 0x35, 0x4e, 0x62, 0xdc, 0xcc,
	0x0d, 0xc9, 0x59, 0x94, 0xf6, 0x72, 0xfd, 0x06, 0x67, 0xd5, 0xc8, 0x39, 0x2b, 0xa9, 0xff, 0xeb,
	0x6d, 0xf4, 0x8d, 0xed, 0x16, 0x8c, 0x20, 0x0d, 0xb0, 0x3a, 0x8f, 0x77, 0x77, 0x3f, 0x8f, 0x6d,
	0xbf, 0x48, 0xc8, 0x04, 0xa8, 0x17, 0x24, 0x25, 0x38, 0x5e, 0x19, 0xbe, 0xbc, 0x93, 0xd6, 0xe9,
	0xd5, 0xd4, 0xd6, 0xaf, 0xa7, 0xb6, 0xfe, 0x6b, 0x6a, 0xeb, 0x5f, 0x67, 0xb6, 0x76, 0x3d, 0xb3,
	0xb5, 0x1f, 0x33, 0x5b, 0xbb, 0x38, 0xf0, 0x09, 0xf7, 0xc7, 0xc1, 0x10, 0xf3, 0x26, 0x4b, 0x42,
	0x17, 0xe1, 0x80, 0xc4, 0x30, 0xe2, 0x18, 0xc6, 0x6e, 0xc8, 0x1a, 0x94, 0x21, 0xec, 0x7e, 0x76,
	0x97, 0xef, 0xa3, 0x9c, 0xc1, 0xdf, 0x92, 0xcf, 0xde, 0xc1, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xe7, 0x22, 0xc0, 0xf1, 0x39, 0x05, 0x00, 0x00,
}

func (m *DelegationNFT) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegationNFT) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegationNFT) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Coin.Size()
		i -= size
		if _, err := m.Coin.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDelegationNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.Quantity.Size()
		i -= size
		if _, err := m.Quantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDelegationNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.TokenID) > 0 {
		i -= len(m.TokenID)
		copy(dAtA[i:], m.TokenID)
		i = encodeVarintDelegationNft(dAtA, i, uint64(len(m.TokenID)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintDelegationNft(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.ValidatorAddress.Size()
		i -= size
		if _, err := m.ValidatorAddress.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDelegationNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.DelegatorAddress.Size()
		i -= size
		if _, err := m.DelegatorAddress.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDelegationNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *UnbondingDelegationNFTEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnbondingDelegationNFTEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnbondingDelegationNFTEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Balance.Size()
		i -= size
		if _, err := m.Balance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDelegationNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.Quantity.Size()
		i -= size
		if _, err := m.Quantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDelegationNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.TokenID) > 0 {
		i -= len(m.TokenID)
		copy(dAtA[i:], m.TokenID)
		i = encodeVarintDelegationNft(dAtA, i, uint64(len(m.TokenID)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintDelegationNft(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.CompletionTime.Size()
		i -= size
		if _, err := m.CompletionTime.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDelegationNft(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.CreationHeight != 0 {
		i = encodeVarintDelegationNft(dAtA, i, uint64(m.CreationHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDelegationNft(dAtA []byte, offset int, v uint64) int {
	offset -= sovDelegationNft(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DelegationNFT) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DelegatorAddress.Size()
	n += 1 + l + sovDelegationNft(uint64(l))
	l = m.ValidatorAddress.Size()
	n += 1 + l + sovDelegationNft(uint64(l))
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovDelegationNft(uint64(l))
	}
	l = len(m.TokenID)
	if l > 0 {
		n += 1 + l + sovDelegationNft(uint64(l))
	}
	l = m.Quantity.Size()
	n += 1 + l + sovDelegationNft(uint64(l))
	l = m.Coin.Size()
	n += 1 + l + sovDelegationNft(uint64(l))
	return n
}

func (m *UnbondingDelegationNFTEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreationHeight != 0 {
		n += 1 + sovDelegationNft(uint64(m.CreationHeight))
	}
	l = m.CompletionTime.Size()
	n += 1 + l + sovDelegationNft(uint64(l))
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovDelegationNft(uint64(l))
	}
	l = len(m.TokenID)
	if l > 0 {
		n += 1 + l + sovDelegationNft(uint64(l))
	}
	l = m.Quantity.Size()
	n += 1 + l + sovDelegationNft(uint64(l))
	l = m.Balance.Size()
	n += 1 + l + sovDelegationNft(uint64(l))
	return n
}

func sovDelegationNft(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDelegationNft(x uint64) (n int) {
	return sovDelegationNft(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DelegationNFT) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDelegationNft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegationNFT: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegationNFT: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDelegationNft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegatorAddress.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDelegationNft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorAddress.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelegationNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelegationNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDelegationNft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Quantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDelegationNft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDelegationNft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnbondingDelegationNFTEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDelegationNft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnbondingDelegationNFTEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnbondingDelegationNFTEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationHeight", wireType)
			}
			m.CreationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionTime", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDelegationNft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CompletionTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelegationNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDelegationNft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDelegationNft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Quantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDelegationNft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDelegationNft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDelegationNft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDelegationNft(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDelegationNft
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDelegationNft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDelegationNft
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDelegationNft
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDelegationNft
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDelegationNft        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDelegationNft          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDelegationNft = fmt.Errorf("proto: unexpected end of group")
)
