// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: validator/validator.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_crypto_types "github.com/cosmos/cosmos-sdk/crypto/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Validator struct {
	ValAddress              string                                           `protobuf:"bytes,1,opt,name=ValAddress,proto3" json:"val_address" yaml:"val_address"`
	PubKey                  github_com_cosmos_cosmos_sdk_crypto_types.PubKey `protobuf:"bytes,2,opt,name=PubKey,proto3,customtype=github.com/cosmos/cosmos-sdk/crypto/types.PubKey" json:"pub_key" yaml:"pub_key"`
	Tokens                  github_com_cosmos_cosmos_sdk_types.Int           `protobuf:"bytes,3,opt,name=Tokens,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"val_address" yaml:"val_address"`
	Status                  BondStatus                                       `protobuf:"bytes,4,opt,name=Status,proto3,customtype=BondStatus" json:"status" yaml:"status"`
	Commission              github_com_cosmos_cosmos_sdk_types.Dec           `protobuf:"bytes,5,opt,name=Commission,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"comission" yaml:"comission"`
	Jailed                  bool                                             `protobuf:"varint,6,opt,name=Jailed,proto3" json:"jailed" yaml:"jailed"`
	UnbondingCompletionTime time.Time                                        `protobuf:"bytes,7,opt,name=UnbondingCompletionTime,proto3,customtype=time.Time" json:"unbonding_completion_time" yaml:"unbonding_completion_time"`
	UnbondingHeight         int64                                            `protobuf:"varint,8,opt,name=UnbondingHeight,proto3" json:"unbonding_height" yaml:"unbonding_height"`
	Description             Description                                      `protobuf:"bytes,9,opt,name=Description,proto3" json:"description" yaml:"description"`
	AccumRewards            github_com_cosmos_cosmos_sdk_types.Int           `protobuf:"bytes,10,opt,name=AccumRewards,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"accum_rewards" yaml:"accum_rewards"`
	RewardAddress           string                                           `protobuf:"bytes,11,opt,name=RewardAddress,proto3" json:"reward_address" yaml:"reward_address"`
	Online                  bool                                             `protobuf:"varint,12,opt,name=Online,proto3" json:"online" yaml:"online"`
}

func (m *Validator) Reset()      { *m = Validator{} }
func (*Validator) ProtoMessage() {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_e972accd7c1f0747, []int{0}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return m.Size()
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

type Description struct {
	Moniker         string `protobuf:"bytes,1,opt,name=Moniker,proto3" json:"moniker" yaml:"moniker"`
	Identity        string `protobuf:"bytes,2,opt,name=Identity,proto3" json:"identity" yaml:"identity"`
	Website         string `protobuf:"bytes,3,opt,name=Website,proto3" json:"website" yaml:"website"`
	SecurityContact string `protobuf:"bytes,4,opt,name=SecurityContact,proto3" json:"security_contact" yaml:"security_contact"`
	Details         string `protobuf:"bytes,5,opt,name=Details,proto3" json:"details" yaml:"details"`
}

func (m *Description) Reset()         { *m = Description{} }
func (m *Description) String() string { return proto.CompactTextString(m) }
func (*Description) ProtoMessage()    {}
func (*Description) Descriptor() ([]byte, []int) {
	return fileDescriptor_e972accd7c1f0747, []int{1}
}
func (m *Description) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Description) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Description.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Description) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Description.Merge(m, src)
}
func (m *Description) XXX_Size() int {
	return m.Size()
}
func (m *Description) XXX_DiscardUnknown() {
	xxx_messageInfo_Description.DiscardUnknown(m)
}

var xxx_messageInfo_Description proto.InternalMessageInfo

type Params struct {
	UnbondingTime     time.Duration `protobuf:"varint,1,opt,name=UnbondingTime,proto3,casttype=time.Duration" json:"unbonding_time" yaml:"unbonding_time"`
	MaxValidators     uint32        `protobuf:"varint,2,opt,name=MaxValidators,proto3" json:"max_validators" yaml:"max_validators"`
	MaxEntries        uint32        `protobuf:"varint,3,opt,name=MaxEntries,proto3" json:"max_entries" yaml:"max_entries"`
	BondDenom         string        `protobuf:"bytes,4,opt,name=BondDenom,proto3" json:"bond_denom" yaml:"bond_denom"`
	HistoricalEntries uint32        `protobuf:"varint,5,opt,name=HistoricalEntries,proto3" json:"historical_entries" yaml:"historical_entries"`
	MaxDelegations    uint32        `protobuf:"varint,6,opt,name=MaxDelegations,proto3" json:"max_delegations" yaml:"max_delegations"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e972accd7c1f0747, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

type BechValidator struct {
	ValAddress string `protobuf:"bytes,1,opt,name=ValAddress,proto3" json:"val_address" yaml:"val_address"`
	// todo
	PubKey                  github_com_cosmos_cosmos_sdk_crypto_types.PubKey `protobuf:"bytes,2,opt,name=PubKey,proto3,customtype=github.com/cosmos/cosmos-sdk/crypto/types.PubKey" json:"pub_key" yaml:"pub_key"`
	Tokens                  github_com_cosmos_cosmos_sdk_types.Int           `protobuf:"bytes,3,opt,name=Tokens,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"val_address" yaml:"val_address"`
	Status                  BondStatus                                       `protobuf:"bytes,4,opt,name=Status,proto3,customtype=BondStatus" json:"status" yaml:"status"`
	Commission              github_com_cosmos_cosmos_sdk_types.Dec           `protobuf:"bytes,5,opt,name=Commission,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"comission" yaml:"comission"`
	Jailed                  bool                                             `protobuf:"varint,6,opt,name=Jailed,proto3" json:"jailed" yaml:"jailed"`
	UnbondingCompletionTime time.Time                                        `protobuf:"bytes,7,opt,name=UnbondingCompletionTime,proto3,customtype=time.Time" json:"unbonding_completion_time" yaml:"unbonding_completion_time"`
	UnbondingHeight         int64                                            `protobuf:"varint,8,opt,name=UnbondingHeight,proto3" json:"unbonding_height" yaml:"unbonding_height"`
	Description             Description                                      `protobuf:"bytes,9,opt,name=Description,proto3" json:"description" yaml:"description"`
	AccumRewards            github_com_cosmos_cosmos_sdk_types.Int           `protobuf:"bytes,10,opt,name=AccumRewards,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"accum_rewards" yaml:"accum_rewards"`
	RewardAddress           string                                           `protobuf:"bytes,11,opt,name=RewardAddress,proto3" json:"reward_address" yaml:"reward_address"`
	Online                  bool                                             `protobuf:"varint,12,opt,name=Online,proto3" json:"online" yaml:"online"`
}

func (m *BechValidator) Reset()         { *m = BechValidator{} }
func (m *BechValidator) String() string { return proto.CompactTextString(m) }
func (*BechValidator) ProtoMessage()    {}
func (*BechValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_e972accd7c1f0747, []int{3}
}
func (m *BechValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BechValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BechValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BechValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BechValidator.Merge(m, src)
}
func (m *BechValidator) XXX_Size() int {
	return m.Size()
}
func (m *BechValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_BechValidator.DiscardUnknown(m)
}

var xxx_messageInfo_BechValidator proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Validator)(nil), "validator.Validator")
	proto.RegisterType((*Description)(nil), "validator.Description")
	proto.RegisterType((*Params)(nil), "validator.Params")
	proto.RegisterType((*BechValidator)(nil), "validator.bechValidator")
}

func init() { proto.RegisterFile("validator/validator.proto", fileDescriptor_e972accd7c1f0747) }

var fileDescriptor_e972accd7c1f0747 = []byte{
	// 1064 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xf7, 0xf6, 0x8f, 0x9b, 0x9d, 0xc4, 0x49, 0xbb, 0x4a, 0x5b, 0x27, 0x08, 0x8f, 0x35, 0x08,
	0x14, 0x84, 0x62, 0x23, 0x72, 0x40, 0x0a, 0x5c, 0xe2, 0x38, 0x52, 0x03, 0x8a, 0x5a, 0x26, 0x4d,
	0x2b, 0xb8, 0x58, 0xe3, 0xdd, 0x91, 0x33, 0xd8, 0xbb, 0x63, 0xed, 0x8e, 0xdb, 0x58, 0x7c, 0x81,
	0x48, 0x20, 0xc1, 0x11, 0x6e, 0xe9, 0x77, 0xe0, 0x43, 0xf4, 0x58, 0x71, 0x42, 0x3d, 0x8c, 0x50,
	0x72, 0x41, 0x7b, 0xf4, 0x91, 0x13, 0x9a, 0x3f, 0xde, 0x5d, 0x3b, 0x2a, 0xa2, 0x3d, 0xe7, 0xe4,
	0xdd, 0xdf, 0x7b, 0xef, 0xf7, 0x7b, 0x33, 0xf3, 0xde, 0xf3, 0x2c, 0x58, 0x7b, 0x46, 0x06, 0x2c,
	0x20, 0x82, 0xc7, 0xcd, 0xec, 0xa9, 0x31, 0x8c, 0xb9, 0xe0, 0x9e, 0x9b, 0x01, 0xeb, 0xab, 0x3d,
	0xde, 0xe3, 0x1a, 0x6d, 0xaa, 0x27, 0xe3, 0xb0, 0xbe, 0xe6, 0xf3, 0x24, 0xe4, 0x49, 0xc7, 0x18,
	0xcc, 0x8b, 0x31, 0xa1, 0x1f, 0x5d, 0xe0, 0x3e, 0x99, 0x86, 0x7b, 0x7b, 0x00, 0x3c, 0x21, 0x83,
	0x9d, 0x20, 0x88, 0x69, 0x92, 0x54, 0x9d, 0xba, 0xb3, 0xe1, 0xb6, 0x3e, 0x4c, 0x25, 0x5c, 0x7c,
	0x46, 0x06, 0x1d, 0x62, 0xe0, 0x89, 0x84, 0xde, 0x98, 0x84, 0x83, 0x6d, 0x54, 0x00, 0x11, 0x2e,
	0x04, 0x7a, 0x21, 0x28, 0x3f, 0x1a, 0x75, 0xbf, 0xa6, 0xe3, 0xea, 0xb5, 0xba, 0xb3, 0xb1, 0xd4,
	0x3a, 0x7a, 0x29, 0x61, 0xe9, 0xb5, 0x84, 0x9f, 0xf6, 0x98, 0x38, 0x1e, 0x75, 0x1b, 0x3e, 0x0f,
	0x6d, 0x16, 0xf6, 0x67, 0x33, 0x09, 0xfa, 0x4d, 0x3f, 0x1e, 0x0f, 0x05, 0x6f, 0x8a, 0xf1, 0x90,
	0x26, 0x0d, 0x13, 0x9f, 0x4a, 0x78, 0x6b, 0x38, 0xea, 0x76, 0xfa, 0x74, 0x3c, 0x91, 0x70, 0xd9,
	0xc8, 0x5a, 0x00, 0x61, 0x2b, 0xe2, 0xf5, 0x41, 0xf9, 0x31, 0xef, 0xd3, 0x28, 0xa9, 0x5e, 0xd7,
	0x19, 0x1f, 0x5a, 0xb9, 0x8f, 0xfe, 0x53, 0xce, 0xe8, 0xec, 0x47, 0xe2, 0xff, 0xad, 0xcf, 0x4a,
	0x78, 0x7b, 0xa0, 0x7c, 0x28, 0x88, 0x18, 0x25, 0xd5, 0x1b, 0x7a, 0x6d, 0x9b, 0x56, 0x0c, 0xb4,
	0x78, 0x14, 0x18, 0x4b, 0x2a, 0x61, 0x39, 0xd1, 0x4f, 0x13, 0x09, 0x2b, 0x86, 0xcb, 0xbc, 0x23,
	0x6c, 0x83, 0x3d, 0x0e, 0xc0, 0x2e, 0x0f, 0x43, 0x96, 0x24, 0x8c, 0x47, 0xd5, 0x9b, 0x3a, 0xef,
	0x87, 0x6f, 0x91, 0x77, 0x9b, 0xfa, 0xa9, 0x84, 0xae, 0xcf, 0x2d, 0xc5, 0x44, 0xc2, 0xdb, 0x46,
	0x29, 0x83, 0x10, 0x2e, 0x48, 0x78, 0x5b, 0xa0, 0xfc, 0x15, 0x61, 0x03, 0x1a, 0x54, 0xcb, 0x75,
	0x67, 0x63, 0xa1, 0xf5, 0x9e, 0xca, 0xf2, 0x7b, 0x8d, 0xe4, 0x59, 0x9a, 0x77, 0x84, 0xad, 0xab,
	0xf7, 0x93, 0x03, 0xee, 0x1f, 0x45, 0x5d, 0x1e, 0x05, 0x2c, 0xea, 0xed, 0xf2, 0x70, 0x38, 0xa0,
	0x82, 0xf1, 0xe8, 0x31, 0x0b, 0x69, 0xf5, 0x96, 0xce, 0x19, 0xdb, 0x9c, 0x5d, 0xc1, 0x42, 0xda,
	0x50, 0x86, 0x54, 0xc2, 0xb5, 0xd1, 0x34, 0xa6, 0xe3, 0x67, 0x41, 0x1d, 0xe5, 0x31, 0x91, 0xb0,
	0x6e, 0xa4, 0xde, 0xe8, 0x82, 0xf0, 0x9b, 0x24, 0xbd, 0x6f, 0xc1, 0x4a, 0x66, 0x7a, 0x40, 0x59,
	0xef, 0x58, 0x54, 0x17, 0xea, 0xce, 0xc6, 0xf5, 0x56, 0x33, 0x95, 0xf0, 0x76, 0xce, 0x78, 0xac,
	0x6d, 0x13, 0x09, 0xef, 0xcf, 0x6b, 0x19, 0x0b, 0xc2, 0xf3, 0x3c, 0x9e, 0x0f, 0x16, 0xdb, 0x34,
	0xf1, 0x63, 0x36, 0x54, 0x6a, 0x55, 0xb7, 0xee, 0x6c, 0x2c, 0x7e, 0x76, 0xaf, 0x91, 0xb7, 0x5a,
	0xc1, 0xda, 0xfa, 0x58, 0x2d, 0x5a, 0x95, 0x4d, 0x90, 0x83, 0x79, 0xd9, 0x14, 0x40, 0x84, 0x8b,
	0xac, 0xde, 0x0f, 0x60, 0x69, 0xc7, 0xf7, 0x47, 0x21, 0xa6, 0xcf, 0x49, 0x1c, 0x24, 0x55, 0xa0,
	0xb7, 0xf0, 0xe9, 0x5b, 0x97, 0x6b, 0x85, 0x28, 0x96, 0x4e, 0x6c, 0x68, 0x26, 0x12, 0xae, 0x1a,
	0xe5, 0x19, 0x18, 0xe1, 0x19, 0x31, 0xef, 0x1b, 0x50, 0x31, 0x8f, 0xd3, 0xf6, 0x5e, 0xd4, 0xea,
	0x9f, 0xa4, 0x12, 0x2e, 0x9b, 0x90, 0x42, 0x07, 0xdc, 0x35, 0x84, 0xb3, 0x38, 0xc2, 0xb3, 0x0c,
	0xaa, 0xa6, 0x1e, 0x46, 0x03, 0x16, 0xd1, 0xea, 0x52, 0x5e, 0x53, 0x5c, 0x23, 0x79, 0x4d, 0x99,
	0x77, 0x84, 0xad, 0xeb, 0xf6, 0xfa, 0xe9, 0x19, 0x2c, 0xfd, 0x7a, 0x06, 0x4b, 0x7f, 0x9f, 0xc1,
	0xd2, 0x1f, 0xbf, 0x6f, 0x82, 0x6c, 0xfc, 0xec, 0xa3, 0xd7, 0xd7, 0x66, 0x8e, 0xc1, 0xfb, 0x1c,
	0xdc, 0x3a, 0xe0, 0x11, 0xeb, 0xd3, 0xd8, 0x0e, 0xa3, 0xf7, 0xd5, 0x44, 0x08, 0x0d, 0x94, 0x4f,
	0x04, 0x0b, 0x20, 0x3c, 0xf5, 0xf6, 0xbe, 0x00, 0x0b, 0xfb, 0x01, 0x8d, 0x04, 0x13, 0x66, 0x06,
	0xb9, 0x2d, 0x98, 0x4a, 0xb8, 0xc0, 0x2c, 0x36, 0x91, 0x70, 0xc5, 0x84, 0x4e, 0x11, 0x84, 0xb3,
	0x00, 0xa5, 0xfa, 0x94, 0x76, 0x13, 0x26, 0xa8, 0x1d, 0x28, 0x5a, 0xf5, 0xb9, 0x81, 0x72, 0x55,
	0x0b, 0x20, 0x3c, 0xf5, 0x56, 0xf5, 0x79, 0x48, 0xfd, 0x51, 0xcc, 0xc4, 0x78, 0x97, 0x47, 0x82,
	0xf8, 0x42, 0x0f, 0x09, 0xd7, 0xd4, 0x67, 0x62, 0x4d, 0x1d, 0xdf, 0xd8, 0xf2, 0xfa, 0x9c, 0xb7,
	0x20, 0x3c, 0xcf, 0xa3, 0x72, 0x6a, 0x53, 0x41, 0xd8, 0x20, 0xb1, 0xc3, 0x42, 0xe7, 0x14, 0x18,
	0x28, 0xcf, 0xc9, 0x02, 0x08, 0x4f, 0xbd, 0xb7, 0x17, 0x4e, 0xed, 0x56, 0xa3, 0xdf, 0x6e, 0x80,
	0xf2, 0x23, 0x12, 0x93, 0x30, 0xf1, 0xba, 0xa0, 0x92, 0x35, 0x80, 0x6e, 0x66, 0xb5, 0xbb, 0x37,
	0x5a, 0x5f, 0xaa, 0x5a, 0xc8, 0x9b, 0xc5, 0x36, 0xec, 0xdd, 0xf9, 0x26, 0xd2, 0x5d, 0xfa, 0x8f,
	0x84, 0x15, 0xdd, 0xf3, 0xed, 0x51, 0x4c, 0xd4, 0x61, 0xe1, 0x59, 0x4a, 0x55, 0x6f, 0x07, 0xe4,
	0x24, 0x3b, 0xdc, 0x44, 0x9f, 0x43, 0xc5, 0xd4, 0x5b, 0x48, 0x4e, 0x3a, 0x59, 0x6b, 0x15, 0xea,
	0x6d, 0x16, 0x47, 0x78, 0x96, 0x41, 0xfd, 0x3d, 0x1d, 0x90, 0x93, 0xbd, 0x48, 0xc4, 0x8c, 0x9a,
	0x61, 0x5f, 0x31, 0x7f, 0x4f, 0x2a, 0x8e, 0x1a, 0x38, 0xef, 0xc3, 0x02, 0x88, 0x70, 0x21, 0xd0,
	0xdb, 0x01, 0xae, 0x1a, 0xd6, 0x6d, 0x1a, 0xf1, 0xd0, 0x1e, 0xd0, 0x07, 0xa9, 0x84, 0x40, 0x65,
	0xdf, 0x09, 0x14, 0x3a, 0x91, 0xf0, 0x8e, 0x21, 0xc9, 0x31, 0x84, 0xf3, 0x28, 0x8f, 0x80, 0x3b,
	0x0f, 0x58, 0x22, 0x78, 0xcc, 0x7c, 0x32, 0x98, 0x26, 0x74, 0x53, 0x27, 0xb4, 0x95, 0x4a, 0xe8,
	0x1d, 0x67, 0xc6, 0x42, 0x5e, 0x6b, 0x86, 0xf2, 0xb2, 0x0d, 0xe1, 0xcb, 0x6c, 0xde, 0x11, 0x58,
	0x3e, 0x20, 0x27, 0x6d, 0x3a, 0xa0, 0x3d, 0xbd, 0xbf, 0x89, 0x1e, 0xdc, 0x95, 0xd6, 0x66, 0x2a,
	0xe1, 0x8a, 0x5a, 0x5b, 0x90, 0x9b, 0x26, 0x12, 0xde, 0xcb, 0x17, 0x5d, 0x30, 0x20, 0x3c, 0x47,
	0xb2, 0xbd, 0x5a, 0x6c, 0xbf, 0xd3, 0x17, 0xd0, 0x39, 0x7b, 0x01, 0x1d, 0xf4, 0xb3, 0x0b, 0x2a,
	0x5d, 0xea, 0x1f, 0x5f, 0x5d, 0x05, 0xde, 0xf9, 0x2a, 0xe0, 0x5e, 0x5d, 0x05, 0xae, 0xae, 0x02,
	0x57, 0x57, 0x81, 0x77, 0xb9, 0x0a, 0x38, 0x97, 0xaf, 0x02, 0xad, 0x83, 0x97, 0xe7, 0x35, 0xe7,
	0xd5, 0x79, 0xcd, 0xf9, 0xeb, 0xbc, 0xe6, 0xfc, 0x72, 0x51, 0x2b, 0xbd, 0xba, 0xa8, 0x95, 0xfe,
	0xbc, 0xa8, 0x95, 0xbe, 0xdb, 0xea, 0x32, 0xd1, 0x1d, 0xf9, 0x7d, 0x2a, 0x1a, 0x3c, 0xee, 0x35,
	0x03, 0xea, 0xb3, 0x90, 0x0c, 0x04, 0x25, 0x61, 0xb3, 0xc7, 0x37, 0x23, 0x1e, 0xd0, 0xe6, 0x49,
	0xfe, 0x8d, 0x64, 0x76, 0xab, 0x5b, 0xd6, 0x9f, 0x3b, 0x5b, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x66, 0x98, 0x2a, 0xd7, 0x47, 0x0d, 0x00, 0x00,
}

func (m *Validator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Validator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Validator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Online {
		i--
		if m.Online {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if len(m.RewardAddress) > 0 {
		i -= len(m.RewardAddress)
		copy(dAtA[i:], m.RewardAddress)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.RewardAddress)))
		i--
		dAtA[i] = 0x5a
	}
	{
		size := m.AccumRewards.Size()
		i -= size
		if _, err := m.AccumRewards.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size, err := m.Description.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.UnbondingHeight != 0 {
		i = encodeVarintValidator(dAtA, i, uint64(m.UnbondingHeight))
		i--
		dAtA[i] = 0x40
	}
	{
		size := m.UnbondingCompletionTime.Size()
		i -= size
		if _, err := m.UnbondingCompletionTime.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.Jailed {
		i--
		if m.Jailed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.Commission.Size()
		i -= size
		if _, err := m.Commission.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Status.Size()
		i -= size
		if _, err := m.Status.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Tokens.Size()
		i -= size
		if _, err := m.Tokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PubKey.Size()
		i -= size
		if _, err := m.PubKey.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Description) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Description) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Description) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Details) > 0 {
		i -= len(m.Details)
		copy(dAtA[i:], m.Details)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.Details)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SecurityContact) > 0 {
		i -= len(m.SecurityContact)
		copy(dAtA[i:], m.SecurityContact)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.SecurityContact)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Website) > 0 {
		i -= len(m.Website)
		copy(dAtA[i:], m.Website)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.Website)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Identity) > 0 {
		i -= len(m.Identity)
		copy(dAtA[i:], m.Identity)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.Identity)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxDelegations != 0 {
		i = encodeVarintValidator(dAtA, i, uint64(m.MaxDelegations))
		i--
		dAtA[i] = 0x30
	}
	if m.HistoricalEntries != 0 {
		i = encodeVarintValidator(dAtA, i, uint64(m.HistoricalEntries))
		i--
		dAtA[i] = 0x28
	}
	if len(m.BondDenom) > 0 {
		i -= len(m.BondDenom)
		copy(dAtA[i:], m.BondDenom)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.BondDenom)))
		i--
		dAtA[i] = 0x22
	}
	if m.MaxEntries != 0 {
		i = encodeVarintValidator(dAtA, i, uint64(m.MaxEntries))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxValidators != 0 {
		i = encodeVarintValidator(dAtA, i, uint64(m.MaxValidators))
		i--
		dAtA[i] = 0x10
	}
	if m.UnbondingTime != 0 {
		i = encodeVarintValidator(dAtA, i, uint64(m.UnbondingTime))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BechValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BechValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BechValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Online {
		i--
		if m.Online {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if len(m.RewardAddress) > 0 {
		i -= len(m.RewardAddress)
		copy(dAtA[i:], m.RewardAddress)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.RewardAddress)))
		i--
		dAtA[i] = 0x5a
	}
	{
		size := m.AccumRewards.Size()
		i -= size
		if _, err := m.AccumRewards.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size, err := m.Description.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.UnbondingHeight != 0 {
		i = encodeVarintValidator(dAtA, i, uint64(m.UnbondingHeight))
		i--
		dAtA[i] = 0x40
	}
	{
		size := m.UnbondingCompletionTime.Size()
		i -= size
		if _, err := m.UnbondingCompletionTime.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.Jailed {
		i--
		if m.Jailed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.Commission.Size()
		i -= size
		if _, err := m.Commission.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Status.Size()
		i -= size
		if _, err := m.Status.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Tokens.Size()
		i -= size
		if _, err := m.Tokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PubKey.Size()
		i -= size
		if _, err := m.PubKey.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintValidator(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintValidator(dAtA []byte, offset int, v uint64) int {
	offset -= sovValidator(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Validator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	l = m.PubKey.Size()
	n += 1 + l + sovValidator(uint64(l))
	l = m.Tokens.Size()
	n += 1 + l + sovValidator(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovValidator(uint64(l))
	l = m.Commission.Size()
	n += 1 + l + sovValidator(uint64(l))
	if m.Jailed {
		n += 2
	}
	l = m.UnbondingCompletionTime.Size()
	n += 1 + l + sovValidator(uint64(l))
	if m.UnbondingHeight != 0 {
		n += 1 + sovValidator(uint64(m.UnbondingHeight))
	}
	l = m.Description.Size()
	n += 1 + l + sovValidator(uint64(l))
	l = m.AccumRewards.Size()
	n += 1 + l + sovValidator(uint64(l))
	l = len(m.RewardAddress)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	if m.Online {
		n += 2
	}
	return n
}

func (m *Description) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	l = len(m.Identity)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	l = len(m.Website)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	l = len(m.SecurityContact)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	l = len(m.Details)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UnbondingTime != 0 {
		n += 1 + sovValidator(uint64(m.UnbondingTime))
	}
	if m.MaxValidators != 0 {
		n += 1 + sovValidator(uint64(m.MaxValidators))
	}
	if m.MaxEntries != 0 {
		n += 1 + sovValidator(uint64(m.MaxEntries))
	}
	l = len(m.BondDenom)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	if m.HistoricalEntries != 0 {
		n += 1 + sovValidator(uint64(m.HistoricalEntries))
	}
	if m.MaxDelegations != 0 {
		n += 1 + sovValidator(uint64(m.MaxDelegations))
	}
	return n
}

func (m *BechValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	l = m.PubKey.Size()
	n += 1 + l + sovValidator(uint64(l))
	l = m.Tokens.Size()
	n += 1 + l + sovValidator(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovValidator(uint64(l))
	l = m.Commission.Size()
	n += 1 + l + sovValidator(uint64(l))
	if m.Jailed {
		n += 2
	}
	l = m.UnbondingCompletionTime.Size()
	n += 1 + l + sovValidator(uint64(l))
	if m.UnbondingHeight != 0 {
		n += 1 + sovValidator(uint64(m.UnbondingHeight))
	}
	l = m.Description.Size()
	n += 1 + l + sovValidator(uint64(l))
	l = m.AccumRewards.Size()
	n += 1 + l + sovValidator(uint64(l))
	l = len(m.RewardAddress)
	if l > 0 {
		n += 1 + l + sovValidator(uint64(l))
	}
	if m.Online {
		n += 2
	}
	return n
}

func sovValidator(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozValidator(x uint64) (n int) {
	return sovValidator(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Validator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commission", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Commission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jailed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Jailed = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingCompletionTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnbondingCompletionTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingHeight", wireType)
			}
			m.UnbondingHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Description.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccumRewards", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AccumRewards.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Online", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Online = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipValidator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Description) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Description: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Description: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Identity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Identity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Website", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Website = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityContact", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecurityContact = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Details", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Details = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipValidator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingTime", wireType)
			}
			m.UnbondingTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingTime |= time.Duration(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxValidators", wireType)
			}
			m.MaxValidators = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxValidators |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxEntries", wireType)
			}
			m.MaxEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxEntries |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HistoricalEntries", wireType)
			}
			m.HistoricalEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HistoricalEntries |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDelegations", wireType)
			}
			m.MaxDelegations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDelegations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipValidator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BechValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: bechValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: bechValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commission", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Commission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jailed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Jailed = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingCompletionTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnbondingCompletionTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingHeight", wireType)
			}
			m.UnbondingHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Description.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccumRewards", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AccumRewards.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Online", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Online = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipValidator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipValidator(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowValidator
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValidator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthValidator
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupValidator
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthValidator
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthValidator        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowValidator          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupValidator = fmt.Errorf("proto: unexpected end of group")
)
