---
# tasks file 
- name: Install epel-release (need for leveldb)
  dnf:
    name:
      - epel-release
    state: latest
  become: yes

- name: Install required packages (leveldb, snappy)
  dnf:
    name:
      - leveldb
      - snappy
    state: latest
  become: yes

- name: Clear current blockchain state (remove keys and data dir)
  file:
    path: '{{ decimal_data }}'
    state: absent

- name: Create binary dir with parent directories if it not exists
  file:
    path: '{{ decimal_bin }}'
    state: directory
    recurse: yes

- name: Upload decd from artifacts
  copy:
    src: '{{ artifacts }}/decd'
    dest: '{{ decimal_bin }}/decd'
    mode: '{{ decimal_bin_mode }}'

- name: Upload deccli from artifacts
  copy:
    src: '{{ artifacts }}/deccli'
    dest: '{{ decimal_bin }}/deccli'
    mode: '{{ decimal_bin_mode }}'
