---
# tasks file for decimal slave (not validator) nodes
- name: Include tasks for clear data and update binary files
  include: node-common-clear.yml

- name: Node initialization
  shell: '{{ decimal_bin }}/decd init $(hostname) --chain-id={{ chain_id }}'
  register: initialization

- debug: var=initialization

- name: Get genesis blockchain file from validator
  uri:
    url: 'http://{{ src_genesis }}/rpc/genesis'
    return_content: yes
  register: content

- set_fact:
    content: '{{ content.json.result.genesis }}'

- debug: var=content

- name: Save genesis file
  copy:
    content: '{{ content }}'
    dest: '{{ decimal_data }}/daemon/config/genesis.json'
    mode: '0750'

- name: Include tasks with common (master & slave) final actions
  include: node-common-in-last.yml