---
# tasks file for decimal explorer master db
- name: Drop schema "public" with cascade
  postgresql_schema:
    db: explorer
    name: public
    state: absent
    cascade_drop: yes
  become: yes
  become_user: postgres

- name: Create schema "public"
  postgresql_schema:
    db: explorer
    name: public
    state: present
  become: yes
  become_user: postgres

- name: REVOKE ALL ON SCHEMA public FROM public;
  postgresql_privs:
    db: explorer
    state: absent
    privs: ALL
    objs: ALL_IN_SCHEMA
    schema: public
    role: public
  become: yes
  become_user: postgres

- name: GRANT ALL ON SCHEMA public TO explorer;
  postgresql_privs:
    db: explorer
    state: present
    privs: ALL
    objs: ALL_IN_SCHEMA
    schema: public
    role: explorer
  become: yes
  become_user: postgres
