---
# tasks file for decimal explorer master db
- name: Drop schema "public" with cascade
  postgresql_schema:
    db: explorer
    name: public
    state: absent
    cascade_drop: yes
  become: yes
  become_user: postgres
