---
# tasks file for decimal-init
- name: Include tasks for Explorer Indexer Worker node
  include: explorer-worker.yml
  when: ansible_hostname.find('explorer-worker') != -1

- name: Include tasks for Explorer Indexer node
  include: explorer-indexer.yml
  when: ansible_hostname.find('explorer-indexer') != -1

- name: Include tasks for Explorer Master Database
  include: explorer-masterdb.yml
  when: ansible_hostname.find('explorer-db-master') != -1
